### ISSUE TITLE
i think it is a fake.

### ISSUE THREAD

**Issue by zsdlove** [shelld3v/JSshell#2]
It can't excute the system comand,just surpport js expression.You are misleading the fish guys,i think It's just a very Rough work.

**Comment by shelld3v** [comment]
Do you understand what is *JSshell*? It's a shell for javascript, **JS** (javascript) + **SHELL**. This allows you to execute javascript codes in a shell env, like when you execute javascript in the Developer console (by entering `F12` and visit the **Console** tab)! Please don't curse anyone when the problem is from your-self. If you read the README, you can see that I have explained everything. And if you have a passion with system shell, you can visit my other apps (repos). This *JSshell* allows you to execute javascript in other computers (accessing javascript console of another browser from your friends or someone that you doesn't have access to)

**Comment by shelld3v** [comment]
Close then
