### ISSUE TITLE
Can't grab 0.0.0.0:4849 with bind: Try a bigger local port number

### ISSUE THREAD

**Issue by zainulhasan** [shelld3v/JSshell#3]
Hi I am having this issue when connecting to the server. any idea?
![Screenshot_3](https://user-images.githubusercontent.com/10378868/89430002-b494d200-d757-11ea-98cf-aa59736715f9.png)

![Untitled](https://user-images.githubusercontent.com/10378868/89430371-1fdea400-d758-11ea-843e-afa521dc6750.png)

**Comment by shelld3v** [comment]
Have you tried a bigger port number? (8989 for example)

**Comment by shelld3v** [comment]
I just updated my code to print the original error message of the socket. Can you try to reinstall it, re-run it and then give me the error message? Thnks

**Comment by zainulhasan** [comment]
> I just updated my code to print the original error message of the socket. Can you try to reinstall it, re-run it and then give me the error message? Thnks


this is the error I am receiving now.

![image](https://user-images.githubusercontent.com/10378868/89799033-6a8c6180-db46-11ea-934e-d822aae20b8f.png)

**Comment by shelld3v** [comment]
The first thing that made me feel strange here is that my new code will quit the app if there is an error when binding. But what I saw in your screenshot is different. It started listening first and then print that error. Even what, I will still investigate this, thank you for choosing my application ;)

**Comment by zainulhasan** [comment]
Any update?

**Comment by shelld3v** [comment]
I can't reproduce the issue,

**Comment by shelld3v** [comment]
Hi, can you recheck?

**Comment by xrmon** [comment]
Hi, I had a similar problem with the tool today where I'd get the "Address already in use" error whenever I entered a command after the shell connected. I think the problem is that you're not setting SO_REUSEADDR when you first create the socket at line 155, meaning the address is considered 'in use' when you try to create a new socket immediately afterwards in shell().
<img width="611" alt="Screenshot 2020-11-30 at 15 58 42" src="https://user-images.githubusercontent.com/43073671/100632690-0d026780-3325-11eb-9d13-dba5347e26f0.png">


The fix is to insert the line "s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)" directly after line 155:
<img width="596" alt="Screenshot 2020-11-30 at 16 00 27" src="https://user-images.githubusercontent.com/43073671/100632795-2c999000-3325-11eb-818f-c0c2bb0ef0b5.png">

This means that when the socket is recreated after the call to shell(), we don't get the "Address already in use" error. Happy to submit a PR if you like, or you can just copy-paste the above line.

**Comment by shelld3v** [comment]
Thanks

**Comment by shelld3v** [comment]
Hey @xrmon, sorry if this is annoying. Can you give me a screenshot with JSshell like in your latest comment (but not with that buggy message)? I want to add it into README =)

**Comment by xrmon** [comment]
How's this?
<img width="1266" alt="Screenshot 2020-12-07 at 18 04 21" src="https://user-images.githubusercontent.com/43073671/101387785-ddb8a100-38b6-11eb-84b9-80dfe2d5f4fb.png">
<img width="696" alt="Screenshot 2020-12-07 at 18 04 16" src="https://user-images.githubusercontent.com/43073671/101387832-ec9f5380-38b6-11eb-9933-db5399cf0319.png">

**Comment by shelld3v** [comment]
Thank you!! ❤️❤️❤️

**Comment by shelld3v** [comment]
Hi @xrmon, sorry if this is noisy, but some people get confused with your pic because of the `-s example.com`. It should be `-s IP`, can you take another pic with `-s 127.0.0.1`.

Thanks!
